function img = loadRaw2Stack(filename, b_readThumbNail, b_readMiddleFrameOnly)
%function img = loadRaw2Stack(filename, b_readThumbNail, b_readMiddleFrameOnly)
%
% Load raw format generated by Hanchuan Peng as a stack.
% This function is a wrapper to call the actual loadRaw2Stack_c function.
%
% by Hanchuan Peng

if nargin<1,
    help loadRaw2Stack;
    error('Usage: img = loadRaw2Stack(filename, b_readThumbNail, b_readMiddleFrameOnly)');
end;

if exist(filename, 'file')==0,
    error('You have specified a file which does not exist.');
end;

if ~exist('b_readThumbNail', 'var'),
    b_readThumbNail = 0;
end;

if ~exist('b_readMiddleFrameOnly', 'var'),
    b_readMiddleFrameOnly = 0;
end;


img = squeeze(loadRaw2Stack_c(filename, b_readThumbNail, b_readMiddleFrameOnly));
